### QUBO Matrix Multiplication Tutorial

# Quadratic Unconstrained Binary Optimization (QUBO)

This notebook explains matrix multiplication and its relevance to QUBO problems. We also provide Python code to perform matrix multiplication using numpy.


# Matrix Multiplication Basics

Matrix multiplication is a fundamental operation in linear algebra. If $A$ is a $m \times n$ matrix and $B$ is a $n \times p$ matrix, their product $C = A \cdot B$ is a $m \times p$ matrix.

The element $c_{ij}$ in $C$ is calculated as:

$$
c_{ij} = \sum_{k=1}^{n} a_{ik} \cdot b_{kj}
$$

### Example Calculation

Let us consider the following matrices $A$ and $B$:

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}
$$

The product $C = A \cdot B$ will be:

$$
C = \begin{bmatrix} c_{11} & c_{12} \\ c_{21} & c_{22} \end{bmatrix}
$$

Using the formula $c_{ij} = \sum_{k=1}^{n} a_{ik} \cdot b_{kj}$:

1. Calculate $c_{11}$:
$$
c_{11} = (1 \cdot 5) + (2 \cdot 7) = 5 + 14 = 19
$$

2. Calculate $c_{12}$:
$$
c_{12} = (1 \cdot 6) + (2 \cdot 8) = 6 + 16 = 22
$$

3. Calculate $c_{21}$:
$$
c_{21} = (3 \cdot 5) + (4 \cdot 7) = 15 + 28 = 43
$$

4. Calculate $c_{22}$:
$$
c_{22} = (3 \cdot 6) + (4 \cdot 8) = 18 + 32 = 50
$$

Thus, the resulting matrix $C$ is:

$$
C = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}
$$

Let us consider case where the matrix elements represent some equation variables:

$$
A = \begin{bmatrix} a & b \\ c & a \end{bmatrix}, \quad B = \begin{bmatrix} b & c \\ a & b \end{bmatrix}
$$

The product $C = A \cdot B$ will be:

$$
C = \begin{bmatrix} c_{11} & c_{12} \\ c_{21} & c_{22} \end{bmatrix}
$$

Using the formula $c_{ij} = \sum_{k=1}^{n} a_{ik} \cdot b_{kj}$:

1. Calculate $c_{11}$:
$$
c_{11} = (a \cdot b) + (b \cdot a) = ab + ba = 2ab
$$

2. Calculate $c_{12}$:
$$
c_{12} = (a \cdot c) + (b \cdot b) = ac + b^2
$$

3. Calculate $c_{21}$:
$$
c_{21} = (c \cdot b) + (a \cdot a) = cb + a^2
$$

4. Calculate $c_{22}$:
$$
c_{22} = (c \cdot c) + (a \cdot b) = c^2 + ab
$$

Thus, the resulting matrix $C$ is:

$$
C = \begin{bmatrix} 2ab & ac + b^2 \\ cb + a^2 & c^2 + ab \end{bmatrix}
$$

# QUBO Problems and Matrix Multiplication

In QUBO problems, we minimize a quadratic function of binary variables:

$$
f(x) = x^T Q x
$$

- $Q$ is the QUBO matrix (square symmetric matrix).
- $x$ is a binary vector ($x \in \{0, 1\}^n$).

Matrix multiplication calculates the objective function $f(x)$. 

**Steps:**
1. $x^T$ is the transpose of $x$.
2. $Q$ defines the coefficients.
3. $f(x) = x^T Q x$.

# Python Implementation

Below is the Python implementation using `numpy` to perform matrix multiplication and compute the QUBO objective value.

In [1]:
import numpy as np

# Define a QUBO matrix (symmetric)
Q = np.array([
    [1, -1, 2],
    [-1, 3, -2],
    [2, -2, 1]
])

# Define a binary vector
x = np.array([1, 0, 1])  # Example binary configuration

# Perform matrix multiplication: f(x) = x^T Q x
def qubo_objective(Q, x):
    return np.dot(x, np.dot(Q, x))

# Calculate the objective function value
objective_value = qubo_objective(Q, x)

print("QUBO Matrix (Q):")
print(Q)
print("\nBinary Vector (x):")
print(x)
print("\nObjective Function Value (f(x)):")
print(objective_value)

QUBO Matrix (Q):
[[ 1 -1  2]
 [-1  3 -2]
 [ 2 -2  1]]

Binary Vector (x):
[1 0 1]

Objective Function Value (f(x)):
6
